on:
    push:
        branches:
          - master
          
jobs:
  copy_site_job:
    runs-on: ubuntu-latest
    name: build site
    steps:
    - name: current dir 
      run: ls | echo  
    - name: copy files
      run: yes | cp -af ${{ github.workspace }}/gui/public/ ${{ github.workspace }}/docs