on:
    push:
        branches:
          - master
          
jobs:
  copy_site_job:
    runs-on: ubuntu-latest
    name: build site
    steps:
    - uses: actions/checkout@master
    - name: get repo
      uses: actions/checkout@v2

    - name: setup node 
      uses: actions/setup-node@v1
      with:
        node-version: 12.6

    - name: install needed packages and build 
      run:  |
            npm install --save-dev --ignore-scripts install-peers
            npm i
            npm run build --if-present

    - name: copy files to docs folder
      run: yes | cp -af ${{ github.workspace }}/gui/public/* ${{ github.workspace }}/docs

    - name: commit changes
      run: |
        git config --local user.email "ivanangethe1@gmail.com"
        git config --local user.name "ivanange"
        git add -A
        git commit -m "pushing to production" -a
    - name: push changes to production
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}