on:
    push:
        branches:
          - master
          
jobs:
  copy_site_job:
    runs-on: ubuntu-latest
    name: build site
    steps:
    - name: get repo
      uses: actions/checkout@v2

    - name: setup node 
      uses: actions/setup-node@v1
      with:
        node-version: 12.6

    - name: install needed packages and build 
    - run:  npm install --save-dev --ignore-scripts install-peers
    - run:  npm i
    - run:  npm run build --if-present

    - name: copy files
      run: yes | cp -af ${{ github.workspace }}/gui/public/* ${{ github.workspace }}/docs

    - name: push changes to production
    - run: git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORYgit"
    - run: git pull github ${GITHUB_REF}
    - run: git add -A
    - run: git commit -m "pushed to production"
    - run: git push github HEAD:${GITHUB_REF}