on:
    push:
        branches:
          - master
          
jobs:
  copy_site_job:
    runs-on: ubuntu-latest
    name: build site
    steps:
    - name: get repo
      uses: actions/hello-world-javascript-action@v1
      
    - name: copy files
      run: yes | cp -af ${{ github.workspace }}/gui/public/ ${{ github.workspace }}/docs